sudo: required

notifications:
  email: false

language: cpp

env:
 global:
  - DOCKER_TAG=v9.2.0-1

services:
 - docker

before_install:
 - sudo docker pull jsrehak/bart:$DOCKER_TAG
 - ci_env=`bash <(curl -s https://codecov.io/env)`

install:
 - sudo docker run jsrehak/bart:$DOCKER_TAG
 - id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
 - sudo docker cp ../BART $id:/home/bart
 - id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
 - sudo docker commit $id jsrehak/bart:$DOCKER_TAG
 - sudo docker run $ci_env -it -u="root" -d -w="/home/bart/BART" --name bart jsrehak/bart:$DOCKER_TAG

script:
 - docker exec bart cmake -DCMAKE_BUILD_TYPE=Debug .
 - docker exec bart make -j4
 - docker exec bart bash -c "./bart_test"
 - docker exec bart bash -c "mpirun -np 2 --allow-run-as-root --oversubscribe ./bart_test --mpi -l 0"

after_success:
 - docker exec bart bash -c "./coverage.sh"
 - docker cp bart:/home/bart/BART/coverage.info .
 - bash <(curl -s https://codecov.io/bash)
